### ISSUE TITLE
Use gif.setDuration();

### ISSUE THREAD

**Issue by johhnry** [sojamo/animatedgif#1]
Hey,

I recently used your library (really great and useful by the way) and I was wondering if I must specify the `duration` in my code with `gif.setDuration();`
I would like to don't specify it when the duration of my gif is uncertain.

Thanks.

Joseph

**Comment by sojamo** [comment]
without having tested this, you can set the the duration to -1 then the frames will be recorded until you call `gitf.stop()` and `gif.save()` or `gif.saveAs(theFileName)` to write the recorded sequence of frames to a gif (after which you should call `gif.clear()` to clear the recorded frames).

**Comment by johhnry** [comment]
Thanks for your answer.
